name: Deploy to maven.d1s.dev (snapshots)

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

          cache: 'gradle'

      - name: Deploy to maven.d1s.dev (snapshots)
        env:
          MAVEN_D1S_DEV_PASSWORD: ${{ secrets.MAVEN_D1S_DEV_PASSWORD }}
          MAVEN_D1S_DEV_USERNAME: ${{ secrets.MAVEN_D1S_DEV_USERNAME }}
        run: ./gradlew publishAllPublicationsToMavenD1sDevRepositorySnapshotsRepository

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_artifacts
          path: ./build/libs
